language: php
cache: vendor
php:
  - 7.0
  - 7.1

sudo: required

install:
  - phpenv config-rm xdebug.ini
  - composer update --prefer-source --no-interaction --no-progress

script:
  - ./vendor/bin/phpmd src text codesize, controversial, design, naming, unusedcode
  - ./vendor/bin/phpcs -n --colors --standard=PSR2 src
  - phpunit
